// SPDX-License-Identifier: MIT

syntax = "proto3";

package img_streamer;

// see img_streamer_request_entry below for explanation
enum img_streamer_file_protocol {
  SEND_PIPE_END = 0;
  SEND_RECV_MEMFD = 1;
}

// This message is sent from CRIU to the streamer.
// * During dump, it communicates the name of the file that is about to be sent
//   to the streamer.
// * During restore, CRIU requests image files from the streamer. The message is
//   used to communicate the name of the desired file.
//   file_protocol is used to communicate how the file should be sent by streamer:
// * During dump, the client can either send a fully populated memfd with the data
//   or provide the read end of a pipe.
// * During restore, the client can either request a fully populated memfd or provide
//   the write end of a pipe.
message img_streamer_request_entry {
  string filename = 1;
  img_streamer_file_protocol protocol = 2;
}

// This message is sent from the streamer to CRIU for listing all image files
message img_streamer_list_reply_entry {
  repeated string filenames = 1;
}

message marker {
  uint64 seq = 1;
  oneof body {
    // Denotes the filename of the next upcoming markers (denoted as current file)
    string filename = 2;
    // Incoming data for the current file
    uint32 file_data = 3;
    // EOF of current file is reached
    bool file_eof = 4;
    // EOF of image is reached
    bool image_eof = 5;
  }
}
