syntax = "proto3";

package plugins.csx;

service CSX {
  rpc GetPath(GetPathReq) returns (GetPathResp) {}
  rpc ClosePath(ClosePathReq) returns (ClosePathResp) {}
  rpc DeleteObject(DeleteObjectReq) returns (DeleteObjectResp) {}
}

enum Mode {
  READ_ONLY = 0;
  WRITE_ONLY = 1;
}

message GetPathReq {
  string ID = 1;
  Mode Mode = 2;
}

message GetPathResp {
  string ActionID = 1;
  string Path = 2;
}

message ClosePathReq {
  string ID = 1;
  string ActionID = 2;
}

message ClosePathResp {}

message DeleteObjectReq {
  string ID = 1;
}

message DeleteObjectResp {}
