syntax = "proto3";

package plugins.csx;

service CSX {
  rpc Create(CreateReq) returns (CreateResp) {}
  rpc CloseWrite(CloseReq) returns (CloseResp) {}
  rpc CloseRead(CloseReq) returns (CloseResp) {}
  rpc Open(OpenReq) returns (OpenResp) {}
}

message CreateReq {
  string CreateID = 1;
  string ObjectID = 2;
  uint64 Size = 3;
}

message CreateResp {
  string Path = 1;
}

message CloseReq {
  string ActionID = 1;
  string ObjectID = 2;
}

message CloseResp {}

message OpenReq {
  string ReadID = 1;
  string ObjectID = 2;
}

message OpenResp {
  string Path = 1;
}
