syntax = "proto3";

package plugins.csx;

service CSX {
  rpc Create(CreateReq) returns (CreateResp) {}
  rpc CloseWrite(CloseReq) returns (CloseResp) {}
  rpc CloseRead(CloseReq) returns (CloseResp) {}
  rpc Open(OpenReq) returns (OpenResp) {}
  rpc Delete(DeleteReq) returns (DeleteResp) {}
}

message CreateReq {
  string ObjectID = 1;
}

message CreateResp {
  string Path = 1;
  string CreateID = 2;
}

message CloseReq {
  string ActionID = 1;
  string ObjectID = 2;
}

message CloseResp {}

message OpenReq {
  string ObjectID = 1;
}

message OpenResp {
  string Path = 1;
  string ReadID = 2;
}

message DeleteReq {
  string ObjectID = 1;
}

message DeleteResp {}
